version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - kaf-cluster

  kafka-1:
    image: confluentinc/cp-kafka:7.0.1
    container_name: kafka-1
    networks:
      - kaf-cluster    
    depends_on:                                   #bağımlı kesinlikle zookeper ayağa kalkmış olmalı..
      - zookeeper
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092, PLAINTEXT_HOST://localhost:9093   #producers, consumers, brokers
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT, PLAINTEXT_HOST:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      ALLOW_PLAINTEXT_LISTENER: "yes"
      
  kafka-2:
    image: confluentinc/cp-kafka:7.0.1
    container_name: kafka-2
    networks:
      - kaf-cluster    
    depends_on:                                   #bağımlı kesinlikle zookeper ayağa kalkmış olmalı..
      - zookeeper
    ports:
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9092, PLAINTEXT_HOST://localhost:9094   #producers, consumers, brokers
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT, PLAINTEXT_HOST:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      ALLOW_PLAINTEXT_LISTENER: "yes"
      
  kafka-3:
    image: confluentinc/cp-kafka:7.0.1
    container_name: kafka-3
    networks:
      - kaf-cluster    
    depends_on:                                   #bağımlı kesinlikle zookeper ayağa kalkmış olmalı..
      - zookeeper
    ports:
      - "9095:9095"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-3:9092, PLAINTEXT_HOST://localhost:9095   #producers, consumers, brokers
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT, PLAINTEXT_HOST:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      ALLOW_PLAINTEXT_LISTENER: "yes"

  kafdrop:       #For monitor we can use kafdrop                   
    image: obsidiandynamics/kafdrop:3.29.0
    networks:
      - kaf-cluster    
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
    ports:
      - "9000:9000"
    environment: 
      KAFKA_BROKER_CONNECT: kafka-1:9092, kafka-2:9092, kafka-3:9092
networks:
  kaf-cluster:
    driver: bridge      