spring:
  profiles:
    active: local
---
spring:
  profiles: local
  kafka:
    producer:
      bootstrap-servers: localhost:9093,localhost:9094,localhost:9095
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        acks: all   # if it is 1, message is written to a leader(default) (0, 1, all)
    admin:
      properties:
        bootstrap.servers: localhost:9093,localhost:9094,localhost:9095

topic:
  name:
    producer: "car-events"

server:
  port: 8080

---
spring:
  profiles: test
  kafka:
    producer:
      bootsrap-servers: test:9092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

topic:
  name:
    producer: "kafka_topic_v1"

server:
  port: 8080